# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShieldAgent < Formula
  desc "Security middleware proxy for MCP servers and AI agents"
  homepage "https://github.com/itdar/shield-agent"
  version "2.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/itdar/shield-agent/releases/download/v2.1.0/shield-agent_2.1.0_darwin_amd64.tar.gz"
      sha256 "bfeb7ce382f5ec5ef934df89b59245c272a5eec67dcef99954c6278560e3aebc"

      define_method(:install) do
        bin.install "shield-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/itdar/shield-agent/releases/download/v2.1.0/shield-agent_2.1.0_darwin_arm64.tar.gz"
      sha256 "5e409d4abce9eb3bd699c6d9c73313487cd416d492a0496ee29a85e9355ffa6b"

      define_method(:install) do
        bin.install "shield-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/itdar/shield-agent/releases/download/v2.1.0/shield-agent_2.1.0_linux_amd64.tar.gz"
      sha256 "8b0d4056535a3b2c401d6c4675acd2e3ecf8decd2bbe5619ee0dec5c1f96ded5"
      define_method(:install) do
        bin.install "shield-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/itdar/shield-agent/releases/download/v2.1.0/shield-agent_2.1.0_linux_arm64.tar.gz"
      sha256 "5d02e002f6a60729d5b1a4020f5fb8f03732fe6f2bee9331dd7665cd7062c6a7"
      define_method(:install) do
        bin.install "shield-agent"
      end
    end
  end

  test do
    system "#{bin}/shield-agent", "--help"
  end
end
