# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShieldAgent < Formula
  desc "Security middleware proxy for MCP servers and AI agents"
  homepage "https://github.com/itdar/shield-agent-dist"
  version "2.3.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/itdar/shield-agent-dist/releases/download/v2.3.7/shield-agent_2.3.7_darwin_amd64.tar.gz"
      sha256 "29c574011674bc9101ee3a12c575f92b3ec1ed75ffa95f1d1338a3c01c427d88"

      define_method(:install) do
        bin.install "shield-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/itdar/shield-agent-dist/releases/download/v2.3.7/shield-agent_2.3.7_darwin_arm64.tar.gz"
      sha256 "d8255c010c95bcfed8d1988ed6c5de31e07fb18f3d506728d4e92fedabd3f29c"

      define_method(:install) do
        bin.install "shield-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/itdar/shield-agent-dist/releases/download/v2.3.7/shield-agent_2.3.7_linux_amd64.tar.gz"
      sha256 "36422c203cad56de9d844f9e78ff72d7e1eff92b4da2b126070731f7cff68586"
      define_method(:install) do
        bin.install "shield-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/itdar/shield-agent-dist/releases/download/v2.3.7/shield-agent_2.3.7_linux_arm64.tar.gz"
      sha256 "2eb71366de051fcc40138e695e4ba3acc9c329e4f2bffed1a739037c057f528a"
      define_method(:install) do
        bin.install "shield-agent"
      end
    end
  end

  test do
    system "#{bin}/shield-agent", "--help"
  end
end
